### ISSUE TITLE
Chaining handlers

### ISSUE THREAD

**Issue by danielfigueiredo** [kayaniu/restify-router#2]
Is there any way to chain handlers using this library? I tried to but after I return calling `next()` the next function doesn't get called.
```
router.get(
    '/foo/:id',
    function(req, res, next) {
        console.log('Authenticate!');
        return next();
    },
    function(req, res, next) {
        res.send(200);
        return next();
    }
);
```

**Comment by danielfigueiredo** [comment]
Sorry this was my mistake!

**Comment by referentiallytransparent** [comment]
Glad to hear its working, what was the issue?

**Comment by referentiallytransparent** [comment]
Ah I see now, you called `res.send(200)` which would terminate the chain so `next()` won't go through
